import '/imports/startup/client';
import '/imports/startup/both';
import '/imports/api/stuff';
import '/imports/ui/layouts';
import '/imports/ui/pages';
import '/imports/ui/stylesheets/simple-sidebar.css';
// import '/imports/ui/stylesheets/main.css';
import '/imports/ui/stylesheets/reset.css';
import '/imports/ui/scss/style.scss';
import '/imports/ui/partials/_layout.scss';
import '/imports/ui/partials/_mixins.scss';
import '/imports/ui/partials/_variables.scss';
import './imports/ui/js/jquery-3.0.0.min.js';
import './imports/ui/js/modernizr.js';